// pages/index.tsx
// import Head from 'next/head';
import Hero from '@/components/shared/creator-login/Hero';
import MainContent from '@/components/shared/creator-login/Main';

export default function Home() {
    return (
        <div className="min-h-screen bg-gray-100">
            {/* <Head>
                <title>Welcome Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <Hero />
            <MainContent />
        </div>
    );
}
